<a href="https://colab.research.google.com/github/saydulakbarmurad/pytorch/blob/main/torch_initial_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch

In [9]:
#Create a random tensors of size (3, 4, 3)\
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2377, 0.2098, 0.7199, 0.4072],
        [0.2054, 0.8054, 0.9714, 0.0936],
        [0.3069, 0.5746, 0.3530, 0.2100]])

In [10]:
#Create a random tensor with similar shape to an image tensor

random_image_size_tensor= torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

#Zeros and Oners

In [11]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [12]:
zeros.dtype

torch.float32

In [13]:
###Createing a range of tensors and tensors like

In [16]:
one_to_ten= torch.arange(0, 10)
one_to_ten

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
torch.__version__

'2.10.0+cpu'

In [17]:
#Createing tesnors like

ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])